# Generated by Django 5.2.9 on 2026-05-28 10:48

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('integration_name', models.SlugField(help_text='Stable machine name, e.g. make_meta_leads', max_length=150)),
                ('service_account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('enabled_modules', models.JSONField(default=list, help_text="Modules this token can access, e.g. ['crm']")),
                ('permissions', models.JSONField(default=dict, help_text="Nested permissions JSON, e.g. {'crm': {'leads': {'create': true}}}")),
                ('full_access', models.BooleanField(default=False, help_text='Grant all actions for the selected enabled modules.')),
                ('is_active', models.BooleanField(default=True)),
                ('token_jti', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.default_integration_token_expiry, help_text='JWT expiry. Default is approximately 10 years.')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integration_tokens', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_tokens', to='tenants.tenant')),
            ],
            options={
                'db_table': 'integration_tokens',
                'ordering': ['tenant__name', 'name'],
                'unique_together': {('tenant', 'integration_name')},
            },
        ),
    ]
