# Generated by Django 5.0.14 on 2025-12-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User-specific preferences and settings (theme, notifications, dashboard layout, etc.)",
            ),
        ),
    ]
