# Generated by Django 5.0.14 on 2025-11-07 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('database_name', models.CharField(blank=True, help_text='Neon database name', max_length=255, null=True)),
                ('database_url', models.TextField(blank=True, help_text='Neon PostgreSQL connection URL', null=True)),
                ('enabled_modules', models.JSONField(default=list, help_text="List of enabled modules: ['crm', 'whatsapp', 'meetings']")),
                ('settings', models.JSONField(default=dict, help_text='Tenant-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
