# Generated by Django 5.0.14 on 2025-12-01 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image file", upload_to="tenant_gallery/%Y/%m/%d/"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label/key for the image (e.g., 'logo', 'banner', 'profile')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for the image",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of the image in the gallery"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this image is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_images",
                "ordering": ["tenant", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "label"],
                        name="tenant_imag_tenant__6d5424_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="tenant_imag_tenant__dab00a_idx",
                    ),
                ],
                "unique_together": {("tenant", "label")},
            },
        ),
    ]
