# GENERATED — DO NOT EDIT. Source: superadmin/apps/common/permissions_catalog.yaml
# Catalog version: 1

PERMISSION_CATALOG = [{'action': 'enabled',
  'allowed_values': ['boolean'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.full_access.enabled',
  'label': 'Full Admin Access',
  'module': 'admin',
  'resource': 'full_access',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view_reports',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.apps.patients.views.PatientViewSet.statistics'],
  'key': 'hms.patients.view_reports',
  'label': 'View Patient Reports',
  'module': 'hms',
  'resource': 'patients',
  'scope_model': 'none',
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.apps.clinical.views (HMSPermission)'],
  'key': 'hms.clinical.view',
  'label': 'View Clinical Records',
  'module': 'hms',
  'resource': 'clinical',
  'scope_model': 'own_all',
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.apps.clinical.views (HMSPermission)'],
  'key': 'hms.clinical.create',
  'label': 'Create Clinical Records',
  'module': 'hms',
  'resource': 'clinical',
  'scope_model': 'none',
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.apps.clinical.views (HMSPermission)'],
  'key': 'hms.clinical.edit',
  'label': 'Edit Clinical Records',
  'module': 'hms',
  'resource': 'clinical',
  'scope_model': 'own_all',
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.apps.clinical.views (HMSPermission)'],
  'key': 'hms.clinical.delete',
  'label': 'Delete Clinical Records',
  'module': 'hms',
  'resource': 'clinical',
  'scope_model': 'none',
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.apps.inventory.views (HMSPermission)'],
  'key': 'hms.inventory.view',
  'label': 'View Inventory',
  'module': 'hms',
  'resource': 'inventory',
  'scope_model': 'own_all',
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.apps.inventory.views (HMSPermission)'],
  'key': 'hms.inventory.create',
  'label': 'Create Inventory Records',
  'module': 'hms',
  'resource': 'inventory',
  'scope_model': 'none',
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.apps.inventory.views (HMSPermission)'],
  'key': 'hms.inventory.edit',
  'label': 'Edit Inventory',
  'module': 'hms',
  'resource': 'inventory',
  'scope_model': 'own_all',
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.apps.inventory.views (HMSPermission)'],
  'key': 'hms.inventory.delete',
  'label': 'Delete Inventory Records',
  'module': 'hms',
  'resource': 'inventory',
  'scope_model': 'none',
  'status': 'active'},
 {'action': 'manage',
  'alias_of': 'hms.inventory.edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'hms.inventory.manage',
  'label': 'Legacy inventory manage',
  'module': 'hms',
  'resource': 'inventory',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'legacy',
  'alias_of': 'admin.full_access.enabled',
  'allowed_values': ['boolean'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.full_access',
  'label': 'Legacy flat full admin access',
  'module': 'admin',
  'resource': 'full_access',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view_reports',
  'alias_of': 'hms.patients.view_reports',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'billing.view_reports',
  'label': 'Legacy billing reports',
  'module': 'billing',
  'resource': 'billing',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'view',
  'alias_of': None,
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.apps.auth.views.UserViewSet', 'dghms.apps.auth.views.RoleViewSet'],
  'key': 'hms.admin.view',
  'label': 'Legacy HMS admin view',
  'module': 'hms',
  'note': 'Legacy generic admin gate honored by UserViewSet and RoleViewSet; no single canonical '
          'alias — migrate roles to admin.users.* / admin.roles.* / admin.full_access.enabled',
  'resource': 'admin',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'create',
  'alias_of': None,
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.apps.auth.views.UserViewSet', 'dghms.apps.auth.views.RoleViewSet'],
  'key': 'hms.admin.create',
  'label': 'Legacy HMS admin create',
  'module': 'hms',
  'note': 'Legacy generic admin gate honored by UserViewSet and RoleViewSet; no single canonical '
          'alias — migrate roles to admin.users.* / admin.roles.* / admin.full_access.enabled',
  'resource': 'admin',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'edit',
  'alias_of': None,
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.apps.auth.views.UserViewSet', 'dghms.apps.auth.views.RoleViewSet'],
  'key': 'hms.admin.edit',
  'label': 'Legacy HMS admin edit',
  'module': 'hms',
  'note': 'Legacy generic admin gate honored by UserViewSet and RoleViewSet; no single canonical '
          'alias — migrate roles to admin.users.* / admin.roles.* / admin.full_access.enabled',
  'resource': 'admin',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'delete',
  'alias_of': None,
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.apps.auth.views.UserViewSet', 'dghms.apps.auth.views.RoleViewSet'],
  'key': 'hms.admin.delete',
  'label': 'Legacy HMS admin delete',
  'module': 'hms',
  'note': 'Legacy generic admin gate honored by UserViewSet and RoleViewSet; no single canonical '
          'alias — migrate roles to admin.users.* / admin.roles.* / admin.full_access.enabled',
  'resource': 'admin',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view',
  'alias_of': 'hms.patients.view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'patients.view',
  'label': 'Legacy patient view',
  'module': 'legacy',
  'resource': 'patients',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'create',
  'alias_of': 'hms.patients.create',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'patients.create',
  'label': 'Legacy patient create',
  'module': 'legacy',
  'resource': 'patients',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'edit',
  'alias_of': 'hms.patients.edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'patients.edit',
  'label': 'Legacy patient edit',
  'module': 'legacy',
  'resource': 'patients',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'view',
  'alias_of': 'hms.opd.view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'opd.view',
  'label': 'Legacy OPD view',
  'module': 'legacy',
  'resource': 'opd',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'create',
  'alias_of': 'hms.opd.create',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'opd.create',
  'label': 'Legacy OPD create',
  'module': 'legacy',
  'resource': 'opd',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'manage',
  'alias_of': None,
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'opd.manage',
  'label': 'Legacy OPD manage',
  'module': 'legacy',
  'note': 'no runtime equivalent',
  'resource': 'opd',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view',
  'alias_of': 'hms.ipd.view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'ipd.view',
  'label': 'Legacy IPD view',
  'module': 'legacy',
  'resource': 'ipd',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'manage',
  'alias_of': None,
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'ipd.manage',
  'label': 'Legacy IPD manage',
  'module': 'legacy',
  'note': 'no runtime equivalent',
  'resource': 'ipd',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view_record',
  'alias_of': 'hms.clinical.view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'clinical.view_record',
  'label': 'Legacy clinical view record',
  'module': 'legacy',
  'resource': 'clinical',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'create_record',
  'alias_of': 'hms.clinical.create',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'clinical.create_record',
  'label': 'Legacy clinical create record',
  'module': 'legacy',
  'resource': 'clinical',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'manage_forms',
  'alias_of': None,
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'clinical.manage_forms',
  'label': 'Legacy clinical manage forms',
  'module': 'legacy',
  'note': 'no runtime equivalent',
  'resource': 'clinical',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view',
  'alias_of': 'hms.inventory.view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'inventory.view',
  'label': 'Legacy inventory view',
  'module': 'legacy',
  'resource': 'inventory',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'manage',
  'alias_of': 'hms.inventory.edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'inventory.manage',
  'label': 'Legacy inventory manage',
  'module': 'legacy',
  'resource': 'inventory',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view_prescriptions',
  'alias_of': 'hms.pharmacy.view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'pharmacy.view_prescriptions',
  'label': 'Legacy prescription view',
  'module': 'legacy',
  'resource': 'pharmacy',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'dispense',
  'alias_of': 'hms.pharmacy.sell',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'pharmacy.dispense',
  'label': 'Legacy dispense',
  'module': 'legacy',
  'resource': 'pharmacy',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view',
  'alias_of': 'hms.payments.view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['none'],
  'key': 'billing.view',
  'label': 'Legacy billing view',
  'module': 'legacy',
  'resource': 'billing',
  'scope_model': 'own_all',
  'status': 'deprecated'},
 {'action': 'create',
  'alias_of': 'hms.payments.create',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'billing.create',
  'label': 'Legacy billing create',
  'module': 'legacy',
  'resource': 'billing',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'manage',
  'alias_of': 'admin.settings.edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['none'],
  'key': 'settings.manage',
  'label': 'Legacy settings manage',
  'module': 'legacy',
  'resource': 'settings',
  'scope_model': 'none',
  'status': 'deprecated'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.users.view',
  'label': 'Users: View',
  'module': 'admin',
  'resource': 'users',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.users.create',
  'label': 'Users: Create',
  'module': 'admin',
  'resource': 'users',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.users.edit',
  'label': 'Users: Edit',
  'module': 'admin',
  'resource': 'users',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.users.delete',
  'label': 'Users: Delete',
  'module': 'admin',
  'resource': 'users',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.roles.view',
  'label': 'Roles: View',
  'module': 'admin',
  'resource': 'roles',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.roles.create',
  'label': 'Roles: Create',
  'module': 'admin',
  'resource': 'roles',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.roles.edit',
  'label': 'Roles: Edit',
  'module': 'admin',
  'resource': 'roles',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.roles.delete',
  'label': 'Roles: Delete',
  'module': 'admin',
  'resource': 'roles',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.settings.view',
  'label': 'Settings: View',
  'module': 'admin',
  'resource': 'settings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['superadmin.apps.common.permissions.IsTenantAdmin'],
  'key': 'admin.settings.edit',
  'label': 'Settings: Edit',
  'module': 'admin',
  'resource': 'settings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.hospital.view',
  'label': 'Hospital: View',
  'module': 'hms',
  'resource': 'hospital',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit_config',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.hospital.edit_config',
  'label': 'Hospital: Edit Config',
  'module': 'hms',
  'resource': 'hospital',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.hospital.create',
  'label': 'Hospital: Create',
  'module': 'hms',
  'resource': 'hospital',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.hospital.edit',
  'label': 'Hospital: Edit',
  'module': 'hms',
  'resource': 'hospital',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.hospital.delete',
  'label': 'Hospital: Delete',
  'module': 'hms',
  'resource': 'hospital',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.patients.view',
  'label': 'Patients: View',
  'module': 'hms',
  'resource': 'patients',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.patients.create',
  'label': 'Patients: Create',
  'module': 'hms',
  'resource': 'patients',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.patients.edit',
  'label': 'Patients: Edit',
  'module': 'hms',
  'resource': 'patients',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.patients.delete',
  'label': 'Patients: Delete',
  'module': 'hms',
  'resource': 'patients',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.patients.export',
  'label': 'Patients: Export',
  'module': 'hms',
  'resource': 'patients',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.doctors.view',
  'label': 'Doctors: View',
  'module': 'hms',
  'resource': 'doctors',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.doctors.create',
  'label': 'Doctors: Create',
  'module': 'hms',
  'resource': 'doctors',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.doctors.edit',
  'label': 'Doctors: Edit',
  'module': 'hms',
  'resource': 'doctors',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.doctors.delete',
  'label': 'Doctors: Delete',
  'module': 'hms',
  'resource': 'doctors',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.doctors.export',
  'label': 'Doctors: Export',
  'module': 'hms',
  'resource': 'doctors',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'set_availability',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.doctors.set_availability',
  'label': 'Doctors: Set Availability',
  'module': 'hms',
  'resource': 'doctors',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.appointments.view',
  'label': 'Appointments: View',
  'module': 'hms',
  'resource': 'appointments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.appointments.create',
  'label': 'Appointments: Create',
  'module': 'hms',
  'resource': 'appointments',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.appointments.edit',
  'label': 'Appointments: Edit',
  'module': 'hms',
  'resource': 'appointments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.appointments.delete',
  'label': 'Appointments: Delete',
  'module': 'hms',
  'resource': 'appointments',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'cancel',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.appointments.cancel',
  'label': 'Appointments: Cancel',
  'module': 'hms',
  'resource': 'appointments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'reschedule',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.appointments.reschedule',
  'label': 'Appointments: Reschedule',
  'module': 'hms',
  'resource': 'appointments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.view',
  'label': 'Opd: View',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.create',
  'label': 'Opd: Create',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.edit',
  'label': 'Opd: Edit',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.delete',
  'label': 'Opd: Delete',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.export',
  'label': 'Opd: Export',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'consult',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.consult',
  'label': 'Opd: Consult',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'bill',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.bill',
  'label': 'Opd: Bill',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'settings',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.opd.settings',
  'label': 'Opd: Settings',
  'module': 'hms',
  'resource': 'opd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.view',
  'label': 'Ipd: View',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.create',
  'label': 'Ipd: Create',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.edit',
  'label': 'Ipd: Edit',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.delete',
  'label': 'Ipd: Delete',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.export',
  'label': 'Ipd: Export',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'admit',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.admit',
  'label': 'Ipd: Admit',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'discharge',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.discharge',
  'label': 'Ipd: Discharge',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'transfer',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.transfer',
  'label': 'Ipd: Transfer',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'bill',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.ipd.bill',
  'label': 'Ipd: Bill',
  'module': 'hms',
  'resource': 'ipd',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.view',
  'label': 'Diagnostics: View',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.create',
  'label': 'Diagnostics: Create',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.edit',
  'label': 'Diagnostics: Edit',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.delete',
  'label': 'Diagnostics: Delete',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.export',
  'label': 'Diagnostics: Export',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'order',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.order',
  'label': 'Diagnostics: Order',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'report',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.report',
  'label': 'Diagnostics: Report',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'approve',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.diagnostics.approve',
  'label': 'Diagnostics: Approve',
  'module': 'hms',
  'resource': 'diagnostics',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.view',
  'label': 'Pharmacy: View',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.create',
  'label': 'Pharmacy: Create',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.edit',
  'label': 'Pharmacy: Edit',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.delete',
  'label': 'Pharmacy: Delete',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.export',
  'label': 'Pharmacy: Export',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'sell',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.sell',
  'label': 'Pharmacy: Sell',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'stock_adjust',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.stock_adjust',
  'label': 'Pharmacy: Stock Adjust',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'statistics',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.pharmacy.statistics',
  'label': 'Pharmacy: Statistics',
  'module': 'hms',
  'resource': 'pharmacy',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.payments.view',
  'label': 'Payments: View',
  'module': 'hms',
  'resource': 'payments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.payments.create',
  'label': 'Payments: Create',
  'module': 'hms',
  'resource': 'payments',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.payments.edit',
  'label': 'Payments: Edit',
  'module': 'hms',
  'resource': 'payments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.payments.delete',
  'label': 'Payments: Delete',
  'module': 'hms',
  'resource': 'payments',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.payments.export',
  'label': 'Payments: Export',
  'module': 'hms',
  'resource': 'payments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'refund',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.payments.refund',
  'label': 'Payments: Refund',
  'module': 'hms',
  'resource': 'payments',
  'scope_model': 'own_all',
  'sensitive': True,
  'status': 'active'},
 {'action': 'reconcile',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.payments.reconcile',
  'label': 'Payments: Reconcile',
  'module': 'hms',
  'resource': 'payments',
  'scope_model': 'own_all',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.services.view',
  'label': 'Services: View',
  'module': 'hms',
  'resource': 'services',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.services.create',
  'label': 'Services: Create',
  'module': 'hms',
  'resource': 'services',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.services.edit',
  'label': 'Services: Edit',
  'module': 'hms',
  'resource': 'services',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.services.delete',
  'label': 'Services: Delete',
  'module': 'hms',
  'resource': 'services',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.orders.view',
  'label': 'Orders: View',
  'module': 'hms',
  'resource': 'orders',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.orders.create',
  'label': 'Orders: Create',
  'module': 'hms',
  'resource': 'orders',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.orders.edit',
  'label': 'Orders: Edit',
  'module': 'hms',
  'resource': 'orders',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.orders.delete',
  'label': 'Orders: Delete',
  'module': 'hms',
  'resource': 'orders',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'pay',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.orders.pay',
  'label': 'Orders: Pay',
  'module': 'hms',
  'resource': 'orders',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'refund',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.orders.refund',
  'label': 'Orders: Refund',
  'module': 'hms',
  'resource': 'orders',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.panchakarma.view',
  'label': 'Panchakarma: View',
  'module': 'hms',
  'resource': 'panchakarma',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.panchakarma.create',
  'label': 'Panchakarma: Create',
  'module': 'hms',
  'resource': 'panchakarma',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.panchakarma.edit',
  'label': 'Panchakarma: Edit',
  'module': 'hms',
  'resource': 'panchakarma',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.panchakarma.delete',
  'label': 'Panchakarma: Delete',
  'module': 'hms',
  'resource': 'panchakarma',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.webhooks.view',
  'label': 'Webhooks: View',
  'module': 'hms',
  'resource': 'webhooks',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.webhooks.create',
  'label': 'Webhooks: Create',
  'module': 'hms',
  'resource': 'webhooks',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.webhooks.edit',
  'label': 'Webhooks: Edit',
  'module': 'hms',
  'resource': 'webhooks',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['dghms.common.drf_auth.HMSPermission'],
  'key': 'hms.webhooks.delete',
  'label': 'Webhooks: Delete',
  'module': 'hms',
  'resource': 'webhooks',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.leads.view',
  'label': 'Leads: View',
  'module': 'crm',
  'resource': 'leads',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.leads.create',
  'label': 'Leads: Create',
  'module': 'crm',
  'resource': 'leads',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.leads.edit',
  'label': 'Leads: Edit',
  'module': 'crm',
  'resource': 'leads',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.leads.delete',
  'label': 'Leads: Delete',
  'module': 'crm',
  'resource': 'leads',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'export',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.leads.export',
  'label': 'Leads: Export',
  'module': 'crm',
  'resource': 'leads',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.activities.view',
  'label': 'Activities: View',
  'module': 'crm',
  'resource': 'activities',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.activities.create',
  'label': 'Activities: Create',
  'module': 'crm',
  'resource': 'activities',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.activities.edit',
  'label': 'Activities: Edit',
  'module': 'crm',
  'resource': 'activities',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.activities.delete',
  'label': 'Activities: Delete',
  'module': 'crm',
  'resource': 'activities',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.statuses.view',
  'label': 'Statuses: View',
  'module': 'crm',
  'resource': 'statuses',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.statuses.create',
  'label': 'Statuses: Create',
  'module': 'crm',
  'resource': 'statuses',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.statuses.edit',
  'label': 'Statuses: Edit',
  'module': 'crm',
  'resource': 'statuses',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.statuses.delete',
  'label': 'Statuses: Delete',
  'module': 'crm',
  'resource': 'statuses',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.tasks.view',
  'label': 'Tasks: View',
  'module': 'crm',
  'resource': 'tasks',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.tasks.create',
  'label': 'Tasks: Create',
  'module': 'crm',
  'resource': 'tasks',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.tasks.edit',
  'label': 'Tasks: Edit',
  'module': 'crm',
  'resource': 'tasks',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.tasks.delete',
  'label': 'Tasks: Delete',
  'module': 'crm',
  'resource': 'tasks',
  'scope_model': 'own_all',
  'sensitive': True,
  'status': 'active'},
 {'action': 'assign',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.tasks.assign',
  'label': 'Tasks: Assign',
  'module': 'crm',
  'resource': 'tasks',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.meetings.view',
  'label': 'Meetings: View',
  'module': 'crm',
  'resource': 'meetings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.meetings.create',
  'label': 'Meetings: Create',
  'module': 'crm',
  'resource': 'meetings',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.meetings.edit',
  'label': 'Meetings: Edit',
  'module': 'crm',
  'resource': 'meetings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.meetings.delete',
  'label': 'Meetings: Delete',
  'module': 'crm',
  'resource': 'meetings',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'cancel',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.meetings.cancel',
  'label': 'Meetings: Cancel',
  'module': 'crm',
  'resource': 'meetings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.payments.view',
  'label': 'Payments: View',
  'module': 'crm',
  'resource': 'payments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.payments.create',
  'label': 'Payments: Create',
  'module': 'crm',
  'resource': 'payments',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.payments.edit',
  'label': 'Payments: Edit',
  'module': 'crm',
  'resource': 'payments',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.payments.delete',
  'label': 'Payments: Delete',
  'module': 'crm',
  'resource': 'payments',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.settings.view',
  'label': 'Settings: View',
  'module': 'crm',
  'resource': 'settings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'crm.settings.edit',
  'label': 'Settings: Edit',
  'module': 'crm',
  'resource': 'settings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'send',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.messages.send',
  'label': 'Messages: Send',
  'module': 'whatsapp',
  'resource': 'messages',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.messages.view',
  'label': 'Messages: View',
  'module': 'whatsapp',
  'resource': 'messages',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.messages.create',
  'label': 'Messages: Create',
  'module': 'whatsapp',
  'resource': 'messages',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.messages.edit',
  'label': 'Messages: Edit',
  'module': 'whatsapp',
  'resource': 'messages',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.messages.delete',
  'label': 'Messages: Delete',
  'module': 'whatsapp',
  'resource': 'messages',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.templates.view',
  'label': 'Templates: View',
  'module': 'whatsapp',
  'resource': 'templates',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.templates.create',
  'label': 'Templates: Create',
  'module': 'whatsapp',
  'resource': 'templates',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.templates.edit',
  'label': 'Templates: Edit',
  'module': 'whatsapp',
  'resource': 'templates',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.templates.delete',
  'label': 'Templates: Delete',
  'module': 'whatsapp',
  'resource': 'templates',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.campaigns.view',
  'label': 'Campaigns: View',
  'module': 'whatsapp',
  'resource': 'campaigns',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.campaigns.create',
  'label': 'Campaigns: Create',
  'module': 'whatsapp',
  'resource': 'campaigns',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.campaigns.edit',
  'label': 'Campaigns: Edit',
  'module': 'whatsapp',
  'resource': 'campaigns',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.campaigns.delete',
  'label': 'Campaigns: Delete',
  'module': 'whatsapp',
  'resource': 'campaigns',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.sequences.view',
  'label': 'Sequences: View',
  'module': 'whatsapp',
  'resource': 'sequences',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.sequences.create',
  'label': 'Sequences: Create',
  'module': 'whatsapp',
  'resource': 'sequences',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.sequences.edit',
  'label': 'Sequences: Edit',
  'module': 'whatsapp',
  'resource': 'sequences',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.sequences.delete',
  'label': 'Sequences: Delete',
  'module': 'whatsapp',
  'resource': 'sequences',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.settings.view',
  'label': 'Settings: View',
  'module': 'whatsapp',
  'resource': 'settings',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.settings.create',
  'label': 'Settings: Create',
  'module': 'whatsapp',
  'resource': 'settings',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.settings.edit',
  'label': 'Settings: Edit',
  'module': 'whatsapp',
  'resource': 'settings',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'whatsapp.settings.delete',
  'label': 'Settings: Delete',
  'module': 'whatsapp',
  'resource': 'settings',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.providers.view',
  'label': 'Providers: View',
  'module': 'integrations',
  'resource': 'providers',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.connections.view',
  'label': 'Connections: View',
  'module': 'integrations',
  'resource': 'connections',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.connections.create',
  'label': 'Connections: Create',
  'module': 'integrations',
  'resource': 'connections',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.connections.edit',
  'label': 'Connections: Edit',
  'module': 'integrations',
  'resource': 'connections',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.connections.delete',
  'label': 'Connections: Delete',
  'module': 'integrations',
  'resource': 'connections',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.workflows.view',
  'label': 'Workflows: View',
  'module': 'integrations',
  'resource': 'workflows',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.workflows.create',
  'label': 'Workflows: Create',
  'module': 'integrations',
  'resource': 'workflows',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.workflows.edit',
  'label': 'Workflows: Edit',
  'module': 'integrations',
  'resource': 'workflows',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'integrations.workflows.delete',
  'label': 'Workflows: Delete',
  'module': 'integrations',
  'resource': 'workflows',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.calls.view',
  'label': 'Calls: View',
  'module': 'telephony',
  'resource': 'calls',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.calls.create',
  'label': 'Calls: Create',
  'module': 'telephony',
  'resource': 'calls',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.calls.edit',
  'label': 'Calls: Edit',
  'module': 'telephony',
  'resource': 'calls',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.calls.delete',
  'label': 'Calls: Delete',
  'module': 'telephony',
  'resource': 'calls',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.sms.view',
  'label': 'Sms: View',
  'module': 'telephony',
  'resource': 'sms',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.sms.create',
  'label': 'Sms: Create',
  'module': 'telephony',
  'resource': 'sms',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.agents.view',
  'label': 'Agents: View',
  'module': 'telephony',
  'resource': 'agents',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.agents.create',
  'label': 'Agents: Create',
  'module': 'telephony',
  'resource': 'agents',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.agents.edit',
  'label': 'Agents: Edit',
  'module': 'telephony',
  'resource': 'agents',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.agents.delete',
  'label': 'Agents: Delete',
  'module': 'telephony',
  'resource': 'agents',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.callbacks.view',
  'label': 'Callbacks: View',
  'module': 'telephony',
  'resource': 'callbacks',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.settings.view',
  'label': 'Settings: View',
  'module': 'telephony',
  'resource': 'settings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.settings.create',
  'label': 'Settings: Create',
  'module': 'telephony',
  'resource': 'settings',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.settings.edit',
  'label': 'Settings: Edit',
  'module': 'telephony',
  'resource': 'settings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'telephony.settings.delete',
  'label': 'Settings: Delete',
  'module': 'telephony',
  'resource': 'settings',
  'scope_model': 'none',
  'sensitive': True,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'meetings.meetings.view',
  'label': 'Meetings: View',
  'module': 'meetings',
  'resource': 'meetings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'meetings.meetings.create',
  'label': 'Meetings: Create',
  'module': 'meetings',
  'resource': 'meetings',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'meetings.meetings.edit',
  'label': 'Meetings: Edit',
  'module': 'meetings',
  'resource': 'meetings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'meetings.meetings.delete',
  'label': 'Meetings: Delete',
  'module': 'meetings',
  'resource': 'meetings',
  'scope_model': 'own_all',
  'sensitive': True,
  'status': 'active'},
 {'action': 'cancel',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'meetings.meetings.cancel',
  'label': 'Meetings: Cancel',
  'module': 'meetings',
  'resource': 'meetings',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'view',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'tasks.tasks.view',
  'label': 'Tasks: View',
  'module': 'tasks',
  'resource': 'tasks',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'create',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'tasks.tasks.create',
  'label': 'Tasks: Create',
  'module': 'tasks',
  'resource': 'tasks',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'},
 {'action': 'edit',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'tasks.tasks.edit',
  'label': 'Tasks: Edit',
  'module': 'tasks',
  'resource': 'tasks',
  'scope_model': 'own_all',
  'sensitive': False,
  'status': 'active'},
 {'action': 'delete',
  'allowed_values': ['own', 'all'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'tasks.tasks.delete',
  'label': 'Tasks: Delete',
  'module': 'tasks',
  'resource': 'tasks',
  'scope_model': 'own_all',
  'sensitive': True,
  'status': 'active'},
 {'action': 'assign',
  'allowed_values': ['boolean'],
  'enforced_by': ['digicrm.common.permissions.HasDigiPermission'],
  'key': 'tasks.tasks.assign',
  'label': 'Tasks: Assign',
  'module': 'tasks',
  'resource': 'tasks',
  'scope_model': 'none',
  'sensitive': False,
  'status': 'active'}]

ACTIVE_PERMISSION_KEYS = tuple(['admin.full_access.enabled',
 'hms.patients.view_reports',
 'hms.clinical.view',
 'hms.clinical.create',
 'hms.clinical.edit',
 'hms.clinical.delete',
 'hms.inventory.view',
 'hms.inventory.create',
 'hms.inventory.edit',
 'hms.inventory.delete',
 'admin.users.view',
 'admin.users.create',
 'admin.users.edit',
 'admin.users.delete',
 'admin.roles.view',
 'admin.roles.create',
 'admin.roles.edit',
 'admin.roles.delete',
 'admin.settings.view',
 'admin.settings.edit',
 'hms.hospital.view',
 'hms.hospital.edit_config',
 'hms.hospital.create',
 'hms.hospital.edit',
 'hms.hospital.delete',
 'hms.patients.view',
 'hms.patients.create',
 'hms.patients.edit',
 'hms.patients.delete',
 'hms.patients.export',
 'hms.doctors.view',
 'hms.doctors.create',
 'hms.doctors.edit',
 'hms.doctors.delete',
 'hms.doctors.export',
 'hms.doctors.set_availability',
 'hms.appointments.view',
 'hms.appointments.create',
 'hms.appointments.edit',
 'hms.appointments.delete',
 'hms.appointments.cancel',
 'hms.appointments.reschedule',
 'hms.opd.view',
 'hms.opd.create',
 'hms.opd.edit',
 'hms.opd.delete',
 'hms.opd.export',
 'hms.opd.consult',
 'hms.opd.bill',
 'hms.opd.settings',
 'hms.ipd.view',
 'hms.ipd.create',
 'hms.ipd.edit',
 'hms.ipd.delete',
 'hms.ipd.export',
 'hms.ipd.admit',
 'hms.ipd.discharge',
 'hms.ipd.transfer',
 'hms.ipd.bill',
 'hms.diagnostics.view',
 'hms.diagnostics.create',
 'hms.diagnostics.edit',
 'hms.diagnostics.delete',
 'hms.diagnostics.export',
 'hms.diagnostics.order',
 'hms.diagnostics.report',
 'hms.diagnostics.approve',
 'hms.pharmacy.view',
 'hms.pharmacy.create',
 'hms.pharmacy.edit',
 'hms.pharmacy.delete',
 'hms.pharmacy.export',
 'hms.pharmacy.sell',
 'hms.pharmacy.stock_adjust',
 'hms.pharmacy.statistics',
 'hms.payments.view',
 'hms.payments.create',
 'hms.payments.edit',
 'hms.payments.delete',
 'hms.payments.export',
 'hms.payments.refund',
 'hms.payments.reconcile',
 'hms.services.view',
 'hms.services.create',
 'hms.services.edit',
 'hms.services.delete',
 'hms.orders.view',
 'hms.orders.create',
 'hms.orders.edit',
 'hms.orders.delete',
 'hms.orders.pay',
 'hms.orders.refund',
 'hms.panchakarma.view',
 'hms.panchakarma.create',
 'hms.panchakarma.edit',
 'hms.panchakarma.delete',
 'hms.webhooks.view',
 'hms.webhooks.create',
 'hms.webhooks.edit',
 'hms.webhooks.delete',
 'crm.leads.view',
 'crm.leads.create',
 'crm.leads.edit',
 'crm.leads.delete',
 'crm.leads.export',
 'crm.activities.view',
 'crm.activities.create',
 'crm.activities.edit',
 'crm.activities.delete',
 'crm.statuses.view',
 'crm.statuses.create',
 'crm.statuses.edit',
 'crm.statuses.delete',
 'crm.tasks.view',
 'crm.tasks.create',
 'crm.tasks.edit',
 'crm.tasks.delete',
 'crm.tasks.assign',
 'crm.meetings.view',
 'crm.meetings.create',
 'crm.meetings.edit',
 'crm.meetings.delete',
 'crm.meetings.cancel',
 'crm.payments.view',
 'crm.payments.create',
 'crm.payments.edit',
 'crm.payments.delete',
 'crm.settings.view',
 'crm.settings.edit',
 'whatsapp.messages.send',
 'whatsapp.messages.view',
 'whatsapp.messages.create',
 'whatsapp.messages.edit',
 'whatsapp.messages.delete',
 'whatsapp.templates.view',
 'whatsapp.templates.create',
 'whatsapp.templates.edit',
 'whatsapp.templates.delete',
 'whatsapp.campaigns.view',
 'whatsapp.campaigns.create',
 'whatsapp.campaigns.edit',
 'whatsapp.campaigns.delete',
 'whatsapp.sequences.view',
 'whatsapp.sequences.create',
 'whatsapp.sequences.edit',
 'whatsapp.sequences.delete',
 'whatsapp.settings.view',
 'whatsapp.settings.create',
 'whatsapp.settings.edit',
 'whatsapp.settings.delete',
 'integrations.providers.view',
 'integrations.connections.view',
 'integrations.connections.create',
 'integrations.connections.edit',
 'integrations.connections.delete',
 'integrations.workflows.view',
 'integrations.workflows.create',
 'integrations.workflows.edit',
 'integrations.workflows.delete',
 'telephony.calls.view',
 'telephony.calls.create',
 'telephony.calls.edit',
 'telephony.calls.delete',
 'telephony.sms.view',
 'telephony.sms.create',
 'telephony.agents.view',
 'telephony.agents.create',
 'telephony.agents.edit',
 'telephony.agents.delete',
 'telephony.callbacks.view',
 'telephony.settings.view',
 'telephony.settings.create',
 'telephony.settings.edit',
 'telephony.settings.delete',
 'meetings.meetings.view',
 'meetings.meetings.create',
 'meetings.meetings.edit',
 'meetings.meetings.delete',
 'meetings.meetings.cancel',
 'tasks.tasks.view',
 'tasks.tasks.create',
 'tasks.tasks.edit',
 'tasks.tasks.delete',
 'tasks.tasks.assign'])
PERMISSION_BY_KEY = {entry["key"]: entry for entry in PERMISSION_CATALOG}

def get_permission_schema():
    """Build the role-editor schema from active catalog entries."""
    schema = {}
    for entry in PERMISSION_CATALOG:
        if entry["status"] not in ("active", "ui_only"):
            continue
        module = schema.setdefault(entry["module"], {"label": entry["module"].upper(), "resources": {}})
        resource = module["resources"].setdefault(entry["resource"], {"label": entry["resource"].replace("_", " ").title(), "actions": {}})
        resource["actions"][entry["action"]] = ({"type": "scope", "options": ["own", "all"]} if entry["scope_model"] == "own_all" else {"type": "boolean"})
    return schema

PERMISSION_SCHEMA = get_permission_schema()
